package co.sisu.mobile.enums;

/**
 * Created by Brady Groharing on 10/15/2018.
 */

public enum ApiReturnTypes {
    GET_MESSAGE_CENTER,
    GET_CLIENT_SETTINGS,
    GET_AGENT_GOALS,
    GET_TEAMS,
    GET_SETTINGS,
    GET_CLIENTS,
    GET_ACTIVITY_SETTINGS,
    GET_AGENT,
    GET_LEADERBOARDS,
    GET_LEADERBOARD_IMAGE,
    GET_PROFILE_IMAGE,
    GET_TEAM_PARAMS,
    GET_NOTES,
    GET_FIREBASE_DEVICES,
    GET_COLOR_SCHEME,
    GET_LABELS,
    GET_ACTIVITIES,
    CREATE_CLIENT,
    SEND_FEEDBACK,
    CREATE_NOTE,
    SEND_FIREBASE_TOKEN,
    SEND_PUSH_NOTIFICATION,
    UPDATE_ACTIVITIES,
    UPDATE_ACTIVITY_SETTINGS,
    UPDATE_AGENT,
    UPDATE_GOALS,
    UPDATE_PROFILE_IMAGE,
    UPDATE_PROFILE,
    UPDATE_SETTINGS,
    UPDATE_NOTE,
    UPDATE_FIREBASE,
    UPDATE_CLIENT,
    ACTIVATE_CLIENT,
    DELETE_NOTE,
    GET_LEAD_SOURCES,
    GET_TEAM_AGENTS,
    CREATE_APPT_NOTE
}
